CREATE TABLE carlist_ads ( 
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  make TEXT NOT NULL,
  model TEXT NOT NULL, 
  year NUMBER(4),
  mileage INTEGER, 
  content TEXT,
  date_created TIMESTAMP DEFAULT now() NOT NULL 
);