CREATE TABLE IF NOT EXISTS carlist_ads ( 
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  make TEXT NOT NULL,
  model TEXT NOT NULL, 
  price NUMERIC(15,6),
  car_year INTEGER,
  photos_link TEXT NOT NULL,
  mileage INTEGER, 
  content TEXT,
  date_created TIMESTAMP DEFAULT now() NOT NULL
  -- CONSTRAINT car_year_chk CHECK ( car_year SIMILAR TO '[0-9]{4}' )
);