CREATE TABLE IF NOT EXISTS carlist_users ( 
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL UNIQUE, 
  full_name TEXT NOT NULL, 
  password TEXT NOT NULL, 
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

ALTER TABLE carlist_ads
  ADD COLUMN 
    author_id INTEGER REFERENCES carlist_users(id)
    ON DELETE SET NULL;